### ISSUE TITLE
Installing on IntelliJ 14.1 causes fatal error

### ISSUE THREAD

**Issue by marstonstudio** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#34]
I'm unable to launch IntelliJ now after installing. I get the following stack trace

Internal error. Please report to https://youtrack.jetbrains.com

java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.psi.stubs.StubUpdatingIndex'
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:178)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:64)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.psi.stubs.StubUpdatingIndex'
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:248)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:289)
    at com.intellij.util.indexing.FileBasedIndexImpl.initComponent(FileBasedIndexImpl.java:358)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:568)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:359)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:116)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:504)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:486)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    ... 16 more
Caused by: java.lang.IllegalAccessError: tried to access method com.intellij.lang.javascript.types.JSFileElementType.<init>(Lcom/intellij/lang/Language;)V from class com.viatra2.cloud.awselastikbeanstalk.ebextensions.ConfigParserDefinition
    at com.viatra2.cloud.awselastikbeanstalk.ebextensions.ConfigParserDefinition.<clinit>(ConfigParserDefinition.java:21)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
    at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
    at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
    at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
    at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:36)
    at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
    at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
    at com.intellij.lang.LanguageExtension.forLanguage(LanguageExtension.java:55)
    at com.intellij.psi.stubs.CumulativeStubVersion.getCumulativeVersion(CumulativeStubVersion.java:35)
    at com.intellij.psi.stubs.StubUpdatingIndex.getVersion(StubUpdatingIndex.java:206)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:378)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:283)
    ... 29 more

**Comment by viatra2** [comment]
Thanks for reporting, 

The last published version of the plugin indeed does not work with IDEA 14.1, platform has introduced an incompatible changes. 

We will publish the new plugin version targeting 14.1 (with fix for this and other improvements) before Monday.

**Comment by marstonstudio** [comment]
How can I disable the plugin to get my IntelliJ to launch again? I’m on a Mac and I can’t find anything related to viatra2 in my /Applications/IntelliJ IDEA 14.app/Contents/plugins/ folder

Thanks for the help,

Jon Marston

**Comment by borlander** [comment]
Should be at ~/Library/Application\ Support/<product><version>

Sorry for troubles

**Comment by marstonstudio** [comment]
that fixed it and I’m back in business.

thank you for the prompt replies and help getting my Intellij working again.

your plugin is very helpful, I primarily rely on the ebextensions editing.

jon

**Comment by denofevil** [comment]
Hi @viatra2, 
I'm Dennis from WebStorm team. We've changed JavaScript API in version 14.1 and it seems your plugin wasn't detected as incompatible by our compatibility checks. If you need some help migrating to new API, feel free to ping me: dennis.ushakov at jetbrains.com

**Comment by grifjef** [comment]
This crashes Webstorm 10 too.

What did you do to stop the crashes?

**Comment by viatra2** [comment]
We have released 0.8.0 for both IDEA and web-language IDEs.
Also, old versions with open build number were removed from plugin repository, so the issue should not happen in future anymore.
